### ISSUE TITLE
Project Status and usage sample

### ISSUE THREAD

**Issue by walternate** [viniciusccarvalho/spring-cloud-stream-binder-pubsub#1]
Hello,

I was wondering if this code is working or if it is still a WIP and how far from working is it. I was also hoping if there could be a sample to show the configurations and how to hook up to the Google pub/sub source. I would like to contribute to this project but would like to get some basics out of the way if possible.

Thanks

**Comment by viniciusccarvalho** [comment]
Hi we are currently moving to grpc based client, there's a new branch. Project is active, but will move under spring-cloud organization in a couple of weeks. By then I hope to have all docs, examples ready.
